name: safeher
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  supabase_flutter: any
  camera: any
  permission_handler: any
  flutter_background_service: any
  provider: any
  google_fonts: any
  path_provider: any
  url_launcher: any
  geolocator: any
  flutter_html: any
  flutter_map: any
  latlong2: any
  http: any
  speech_to_text: any
  xml: any
  shared_preferences: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/icon/app_icon.jpeg


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/app_icon.jpeg"